# Generated by Django 4.2.13 on 2024-05-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_cliente',
            old_name='rut_cliente',
            new_name='cliente',
        ),
    ]
