# Generated by Django 4.2.13 on 2024-06-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='rut_agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.agente'),
            preserve_default=False,
        ),
    ]
