# Generated by Django 4.2.13 on 2024-06-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_publicacion_id_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='rut_cliente',
        ),
    ]
