# Generated by Django 4.2.13 on 2024-05-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_propiedad_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.FileField(blank=True, null=True, upload_to='media/pdfs/'),
        ),
    ]
